# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0db997c6891c4389174f962a77f78068fc549c3a681a8c60255d23e41ad1c5c8e224da123a5b4f7afc200904f99b3453c556dd5a6e3610188957d93d4008460

test:
  secret_key_base: 5c6c7a27419a230414217d7f64d37d4920c3970edf87499a523e073eca09e696a95fa48f05b1c96261bdd54784831e7704fef232ec31490c7519936dc31bd94d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
